- name: 標準のRubyは使わない
  yum:
    name: ruby
    state: absent

- name: The Software Collections(SCL)リポジトリを追加
  yum:
    name: centos-release-scl
    state: installed

- name: Ruby 2.4をインストール
  yum:
    name:
      - rh-ruby24
      - rh-ruby24-ruby-devel
    state: installed

- name: pam_env.confにPATHの設定を追加
  blockinfile:
    path: /etc/security/pam_env.conf
    block: |
      PATH DEFAULT=/usr/local/bin:/usr/bin:/opt/rh/rh-ruby24/root/usr/local/bin:/opt/rh/rh-ruby24/root/usr/bin
      LD_LIBRARY_PATH DEFAULT=/opt/rh/rh-ruby24/root/usr/local/lib64:/opt/rh/rh-ruby24/root/usr/lib64
      PKG_CONFIG_PATH DEFAULT=/opt/rh/rh-ruby24/root/usr/local/lib64/pkgconfig:/opt/rh/rh-ruby24/root/usr/lib64/pkgconfig

- name: rh-ruby24を優先するように/etc/profile.d/ruby.shを追加
  copy:
    src: profile.sh
    dest: /etc/profile.d/ruby.sh
